# This file was generated by GoReleaser. DO NOT EDIT.
cask "saucectl" do
  version "0.215.0"

  on_macos do
    on_intel do
      sha256 "c9a945e3dfb078c211e304e4d25f72f42871fde5af22e557517eefe25e04bc62"
      url "https://github.com/saucelabs/saucectl/releases/download/v#{version}/saucectl_#{version}_mac_64-bit.tar.gz",
        verified: "github.com/saucelabs/saucectl"
    end
    on_arm do
      sha256 "e0835c9bcada94b95a9b2dfc0e0d017df35e5120fae7ff13d4b52aa28301f435"
      url "https://github.com/saucelabs/saucectl/releases/download/v#{version}/saucectl_#{version}_mac_arm64.tar.gz",
        verified: "github.com/saucelabs/saucectl"
    end
  end

  name "saucectl"
  desc "Test orchestration with Sauce Labs"
  homepage "https://saucelabs.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saucectl"

  # No zap stanza required

end
