# This file was generated by GoReleaser. DO NOT EDIT.
cask "saucectl" do
  version "0.209.0"

  on_macos do
    on_intel do
      sha256 "826c99ee346a97a79ce8c1814c8b083a0587585b03fc68916136a936a64a10ef"
      url "https://github.com/saucelabs/saucectl/releases/download/v#{version}/saucectl_#{version}_mac_64-bit.tar.gz",
        verified: "github.com/saucelabs/saucectl"
    end
    on_arm do
      sha256 "7ffb33524d8668e6a3660f7e0e1b9e7ff4d544045b65d1faecec085069be9540"
      url "https://github.com/saucelabs/saucectl/releases/download/v#{version}/saucectl_#{version}_mac_arm64.tar.gz",
        verified: "github.com/saucelabs/saucectl"
    end
  end

  name "saucectl"
  desc "Test orchestration with Sauce Labs"
  homepage "https://saucelabs.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saucectl"

  # No zap stanza required

end
