# This file was generated by GoReleaser. DO NOT EDIT.
cask "saucectl" do
  version "0.203.1-rc.2"

  on_macos do
    on_intel do
      url "https://github.com/saucelabs/saucectl/releases/download/v#{version}/saucectl_#{version}_mac_64-bit.tar.gz",
        verified: "github.com/saucelabs/saucectl"
      sha256 "d12eb7293070da11ba32421e67b2949304588f799ab0530edf527b5fa2a9effb"
    end
    on_arm do
      url "https://github.com/saucelabs/saucectl/releases/download/v#{version}/saucectl_#{version}_mac_arm64.tar.gz",
        verified: "github.com/saucelabs/saucectl"
      sha256 "4939d01d11658d0ccbb04cea588bb4f248c73a71bccf72c894b01f2bd1d50cf0"
    end
  end

  name "saucectl"
  desc "Test orchestration with Sauce Labs"
  homepage "https://saucelabs.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saucectl"

  # No zap stanza required

end
