# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saucectl < Formula
  desc "Saucectl is a command-line interface to run testrunner tests"
  homepage "https://saucelabs.com/"
  version "0.113.1-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saucelabs/saucectl/releases/download/v0.113.1-alpha/saucectl_0.113.1-alpha_mac_64-bit.tar.gz"
      sha256 "8145de22745301efc426f1625fe9f6f9b998da6c1064ec922dc7ba43b74b2304"

      def install
        bin.install "saucectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saucelabs/saucectl/releases/download/v0.113.1-alpha/saucectl_0.113.1-alpha_mac_arm64.tar.gz"
      sha256 "6b590e105dfd200ae1cfea0be12f584c0d06184099c47c70b656dfc7de1f2b8a"

      def install
        bin.install "saucectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/saucelabs/saucectl/releases/download/v0.113.1-alpha/saucectl_0.113.1-alpha_linux_64-bit.tar.gz"
      sha256 "b831e61e5259f31af8c8412fd80ce42c91c0a8dad30b92cb210312193af60a04"

      def install
        bin.install "saucectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saucelabs/saucectl/releases/download/v0.113.1-alpha/saucectl_0.113.1-alpha_linux_arm64.tar.gz"
      sha256 "7bda47d9875711d8dba27cf841a7737c7581d91e70b8518ecc7185a505391eb0"

      def install
        bin.install "saucectl"
      end
    end
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
