# This file was generated by GoReleaser. DO NOT EDIT.
class SaucectlInternal < Formula
  desc "Homebrew Formulae to saucectl binaries"
  homepage "https://saucelabs.com"
  version "0.3.14"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/saucelabs/saucectl-internal/releases/download/v0.3.14/saucectl-internal_0.3.14_mac_64-bit.tar.gz"
    sha256 "04876453d0877f1f136ae39daf7b9ef1405477493c665f4b35baeb4b30929117"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/saucelabs/saucectl-internal/releases/download/v0.3.14/saucectl-internal_0.3.14_linux_64-bit.tar.gz"
      sha256 "c961b147191b113e16cf98a2bddfca4c0fc3ed61897953e6c4ee4dd38a01c24e"
    end
  end

  def install
    bin.install "saucectl-internal"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
