# This file was generated by GoReleaser. DO NOT EDIT.
class Saucectl < Formula
  desc "A command line interface to run testrunner tests."
  homepage "https://saucelabs.com/"
  version "0.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/saucelabs/saucectl-internal/releases/download/v0.5.1/saucectl_0.5.1_mac_64-bit.tar.gz"
    sha256 "16535e3511a1fc08575652a6654ff1845f91496a0ccbae7c5a41c6685e48c2c3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/saucelabs/saucectl-internal/releases/download/v0.5.1/saucectl_0.5.1_linux_64-bit.tar.gz"
      sha256 "ab93b610f9e0f7edfe8fd26f02365cae8e813727a6005346e8c33a76a01724d8"
    end
  end
  
  depends_on "docker"

  def install
    bin.install "saucectl"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
