# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saucectl < Formula
  desc "Saucectl is a command-line interface to run testrunner tests"
  homepage "https://saucelabs.com/"
  version "0.100.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/saucelabs/saucectl/releases/download/v0.100.5/saucectl_0.100.5_mac_arm64.tar.gz"
      sha256 "727201ad23b00faad66a5518f7584a4aa399dd0f50d3acd2f12c7c0a4f52d032"

      def install
        bin.install "saucectl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/saucelabs/saucectl/releases/download/v0.100.5/saucectl_0.100.5_mac_64-bit.tar.gz"
      sha256 "dd2207c3a4de7b62005b2906c6a473b727770781be265ab6aea3e741c021a758"

      def install
        bin.install "saucectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saucelabs/saucectl/releases/download/v0.100.5/saucectl_0.100.5_linux_arm64.tar.gz"
      sha256 "a0df59a0648dc824e037a3fb10da65c8a3a8398ff2bdb7ea31634146251249c3"

      def install
        bin.install "saucectl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/saucelabs/saucectl/releases/download/v0.100.5/saucectl_0.100.5_linux_64-bit.tar.gz"
      sha256 "bd7ef1fb52693618517fbd64897fa8f07f4bcb0adcfaf791067b914f251463f9"

      def install
        bin.install "saucectl"
      end
    end
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
