name: brew test-bot

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run brew test-bot
        run: |
          set -e
          brew update
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/saucelabs/homebrew-saucectl"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"
          brew test-bot
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Formula
        run: brew audit --strict --formula Formula/saucectl.rb
  test-install:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Formula
        run: |
          brew update
          brew install --formula Formula/saucectl.rb
