name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up tap
        run: |
          mkdir -p "$(brew --repository)/Library/Taps/saucelabs"
          ln -s "$GITHUB_WORKSPACE" "$(brew --repository)/Library/Taps/saucelabs/homebrew-saucectl"
      - name: Audit Formula
        run: brew audit --strict --formula --except=version saucectl
  test-cask:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up tap
        run: |
          mkdir -p "$(brew --repository)/Library/Taps/saucelabs"
          ln -s "$GITHUB_WORKSPACE" "$(brew --repository)/Library/Taps/saucelabs/homebrew-saucectl"
      - name: Audit Cask
        run: brew audit --cask saucectl
